### ISSUE TITLE
[Bug]: Keys on up5401ea seem to be doubling

### ISSUE THREAD

**Issue by applecuckoo** [asus-linux-drivers/asus-touchpad-numpad-driver#102]
### Describe the bug

Hi there, sometimes there seems to be key doubling with the up5401ea key layout. The % symbol also seems to be outputting '25 %' without the quotes.

### Expected behavior

I would expect the symbols to only be output once and not duplicate times

### Desktop

- Program version: b443bfc
- Distro: Linux Mint
- Kernel: 5.17.0-1027-oem

**Comment by ldrahnik** [comment]
@applecuckoo Hello, thank you for creating an issue. It looks like the service which starts the driver is doubled from the previous version of the driver, now is possible to install the driver even under the current user. Please download / `git pull` the latest master and reinstall the driver, `sudo ./uninstall.sh`, `sudo ./install.sh` and let me know if it helped.
