### ISSUE TITLE
Try official Asus numpad driver

### ISSUE THREAD

**Issue by ldrahnik** [asus-linux-drivers/asus-touchpad-numpad-driver#17]
for Windows and learn from that experience. [Pointing Device for Zenbook-14-Flip-OLED-UP5401-11th-Gen-Intel ](https://www.asus.com/Laptops/For-Home/Zenbook/Zenbook-14-Flip-OLED-UP5401-11th-Gen-Intel/HelpDesk_Download/).

EDIT: From source [video1](https://www.youtube.com/watch?v=CNpD6IQQf50) is implemented *Show calculator app* functionality, when finger touch left top icon and then slid in direction to other corners. The calculator launch is implemented as touch [in base driver](https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver/blob/main/asus_touchpad.py).

EDIT2: sent request to Asus support (indeed they do not support linux)

**Comment by kamack38** [comment]
There is a very good video showing how the *NumberPad* should work. (https://www.youtube.com/watch?v=8NKvpiejCMo)
