### ISSUE TITLE
Numlock indicator delay

### ISSUE THREAD

**Issue by kamack38** [asus-linux-drivers/asus-touchpad-numpad-driver#3]
I can confirm that the numlock indicator delay occurs.

```
Laptop: ASUS ROG Strix Scar 15 G533QS
OS: Arch Linux
Kernel: 5.18.5-arch1-g14-1 
```

**Comment by ldrahnik** [comment]
Should be fixed [here](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/pull/5). Can you test it and send me feedback, please.

**Comment by kamack38** [comment]
Ok

**Comment by kamack38** [comment]
It seems to be working

**Comment by kamack38** [comment]
Could you please change that if `top_left_icon_width` and `top_left_icon_height` is not set, the *left icon* will be suppressed instead of adding a new setting?
