### ISSUE TITLE
[Feature request] Detect external keyboard automatically

### ISSUE THREAD

**Issue by ldrahnik** [asus-linux-drivers/asus-touchpad-numpad-driver#35]
1. Because now when is changed NumberPad status to disabled, system NumLock is disabled aswell. It should not happens when would be a connected external keyboard.
2. Enabling system NumLock should enable numpad if is not external keyboard connected.

Outside of the scope of this driver anyway the solution is creating `udev` rule when is pressed `NumLock` key with one exception (device added newly by this driver) then when joining external keyboard do:

- set `sys_numlock_enables_numpad=0`
- set `disabling_numpad_disable_sys_numlock=0`
- enable system NumLock when is not enabled yet

and when removing external keyboard:

- disable system NumLock when is not NumberPad `enabled =1`
- set `sys_numlock_enables_numpad=1`
- set `disabling_numpad_disable_sys_numlock=1`

Possibility do this be implemented in issue https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/issues/42

If solved could help who use some time external keyboard and some time not, activation of udev rule could be included in install script.

**Comment by ldrahnik** [comment]
@kamack38 mine external keyboard unfortunately stopped working. Do you have any? We need terminal command which returns whether any (1 or more) external keyboard is connected.

**Comment by kamack38** [comment]
Unfortunately currently I'm on holidays, so I probably won't be able to check it till the end of the holidays.
