### ISSUE TITLE
[Bug]: Problem touch with layout g533

### ISSUE THREAD

**Issue by Gevert92** [asus-linux-drivers/asus-touchpad-numpad-driver#55]
### Describe the bug

Some keys of touch pad using layout g533, does not write correctly.

The keys that type well are "1, 2, 3, 4, 5, 6, *, -, +, Enter".
The slash key (/) does not write.
The keys "0, 7, 8, 9, Back" must be pressed several times to type.

### Expected behavior

Each key must write the value at the first contact.

It is desirable that when leaving the key pressed, the value is written several times.

### Desktop

- Program version [e.g. 57c742a]
- Distro [e.g. Arch Linux]
- Kernel [e.g. 5.18.15.arch1-2]

**Comment by ldrahnik** [comment]
Hello, thank you for creating an issue.  

> It is desirable that when leaving the key pressed, the value is written several times.

For second part please try enable `key_repetitions` in your layout file. So add row `key_repetitions=True`. It is disabled by default.

**Comment by ldrahnik** [comment]
> Each key must write the value at the first contact.

Can you please run driver in debug mode:

> LOG=DEBUG sudo -E ./asus_touchpad.py

and post result?

**Comment by Gevert92** [comment]
Thank you for your response.

For the first point I put key_repetitions and it worked fine.

For the second part I am not sure if I did it right, but I will detail the tests.

First I uncommented the line you indicate.
![image](https://user-images.githubusercontent.com/42220220/185033597-f1acb1a6-b92e-462a-9a84-b5dec7aca763.png)

Then I ran the install.sh and this is the result
![image](https://user-images.githubusercontent.com/42220220/185033723-87df1738-a0d3-44da-b4b0-97affcd026bf.png)

As you can see I had to comment out the line "sudo -E ./asus_touchpad.py" because when running the install.sh, ubuntu experiences a syntax error problem.
![image](https://user-images.githubusercontent.com/42220220/185033787-5e086b7e-b26f-4f92-bf20-e2773a50cc53.png)

**Comment by ldrahnik** [comment]
> Troubleshooting
> To show debug logs run:
> LOG=DEBUG sudo -E ./asus_touchpad.py

Not uncomment line but run command. Readme suggest the same.

**Comment by ldrahnik** [comment]
Closed because of inactivity of issue owner.

**Comment by Gevert92** [comment]
Hi, sorry for the inactivity, I had problems with my pc.

I share the image of the debug, I stopped the service and executed the command

![image](https://user-images.githubusercontent.com/42220220/186040068-3b36b8ea-d15b-4263-ab82-e1e0150550f5.png)

**Comment by ldrahnik** [comment]
Discussion continues here https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/issues/58
