### ISSUE TITLE
[Feature request] Numpad and Touchpad together

### ISSUE THREAD

**Issue by encrustace** [asus-linux-drivers/asus-touchpad-numpad-driver#56]
### Short Description

Can you please implement Touchpad and Numpad works together like windows driver does.
There is already a driver written in Rust and it works in very close to windows.
url in additional info

### Additional Info

https://github.com/iamkroot/asus-numpad

**Comment by encrustace** [comment]
The repository I have mentioned has implemented the same feature, which means we can use the touchpad when Numpad is active. but it's written in rust, let's try to reverse engineer it

**Comment by ldrahnik** [comment]
Can you please more describe that feature. What is expected to do?

**Comment by ldrahnik** [comment]
@encrustace ping

**Comment by encrustace** [comment]
Today I'll try and will update here the result

**Comment by encrustace** [comment]
For starting 10 seconds it works after that touchpad light is glowing but neither the trackpad nor Numpad is working and after rebooting again same.

**Comment by ldrahnik** [comment]
@encrustace Should be fixed now.

**Comment by ldrahnik** [comment]
@encrustace  Let me please know that update fixed this issue.

**Comment by encrustace** [comment]
Ok, I'll test it today and will update

**Comment by ldrahnik** [comment]
@encrustace OK, I look forward to your feedback.

**Comment by encrustace** [comment]
@ldrahnik  Numpad and Trackpad work together fine but in some applications such as notepad where the edit area is always in focus, it types one number from where you start to move the cursor, like if the position is at 5 then it will type 5 and then the cursor will start moving.

**Comment by ldrahnik** [comment]
@encrustace On Windows driver is using of this feature a bit controversial too or it is working perfectly? Do you know? I mean a decision about what to do, touch the number or only do a move.

**Comment by encrustace** [comment]
@ldrahnik  I have never used windows, used windows to just download Linux on this machine so not sure if it was working or not. but one thing you can try is that if the time difference between touch and untouch is very quick (in a certain range) then consider it as touch else its s a cursor move. or another approach could be like if the touch point and untouch point x y axis has a particular distance then it will move else it will be a touch

**Comment by ldrahnik** [comment]
@encrustace In mentioned branch [56-numpad-touchpad-together](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/tree/56-numpad-touchpad-together) I implemented idea add the option to write the NumberPad key when is touch released / touch is untouched (option `press_key_when_is_done_untouch = 1`, by default enabled)  and with disabled option `one_touch_key_rotation = 0` (by default disabled) is done only pointer move when is at least one time crossed border of the key where was touch initialized. Please test it and let me know your feedback.

**Comment by encrustace** [comment]
@ldrahnik This is working amazing, exactly as a user would wanted.

One thing can be improved, I know this is very tough to implement but can be given a thought, like I am typing something is a notepad and I want to correct some word and trying to move edit pointer at a specific line, now it bring pointer to that line but it also typed a number or operation symbol, In simple word what if it could differentiate between type click and focus click. it can be done by comparing the current position of cursor and edit pointer position, but challenge will be checking current  what application is in focus is it an editor or edit box or edit field.

**Comment by encrustace** [comment]
I am not asking, I am just giving feedback, you have done an amazing work already.

**Comment by ldrahnik** [comment]
@encrustace I am afraid, that is not possible to implement. My recommendation is to use the pointer left button when is click done somewhere where is also possible to write number/char. Of course in these moments have an advantages laptops with pointer buttons outside of touchpad area :)
