### ISSUE TITLE
[Bug]: gx551 top row not working

### ISSUE THREAD

**Issue by JamDon2** [asus-linux-drivers/asus-touchpad-numpad-driver#65]
### Describe the bug

Only the numlock part of the top row is working. When pressing the buttons of the row below that it outputs 7 / *.
There is also some overlapping between dot and enter.

### Expected behavior

All buttons are outputting the correct characters.

### Desktop

- Program version: f01431a
- Distro: Ubuntu
- Kernel: 5.15.0-47-generic

**Comment by ldrahnik** [comment]
Hello, thank you for creating in issue. Could you stop systemctl service and run driver in debug mode like described in [Troubleshooting](tttps://github.com/asus-linux-drivers/asus-touchpad-numpad-driver#troubleshooting) in Readme and post here result. Thanks.

**Comment by ldrahnik** [comment]
Can be reopened when will be added corresponding debug log as is the issue description guiding / my message reminded too as well.

**Comment by ldrahnik** [comment]
My attempt at better offsets for gx551 via a photo of the layout has been pushed.
