### ISSUE TITLE
[Bug]: no g533 layout

### ISSUE THREAD

**Issue by satva2** [asus-linux-drivers/asus-touchpad-numpad-driver#68]
### Describe the bug

I posted the other day, and you asked for a screenshot. i was replying from email and it appears the photo i inserted (twice) didnt make its way through.. none the less i appreciate the help. heres a screenshot

also, bear with me. new here. i replied on the closed issue, but wasnt sure if youd see it so im reopening one.

![Screenshot from 2022-09-14 06-32-51](https://user-images.githubusercontent.com/49539747/190132095-769f140c-ee3e-4c63-9957-287f9c9d8316.png)

### Expected behavior

cannot get numpad on g533 working.

### Desktop

- Program version [e.g. 57c742a]
- Distro [e.g. Arch Linux]
- Kernel [e.g. 5.18.15.arch1-2]

**Comment by ldrahnik** [comment]
Duplication of https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/issues/66

**Comment by satva2** [comment]
ok, heres that

![Screenshot from 2022-09-14 06-48-00](https://user-images.githubusercontent.com/49539747/190134748-42843e85-668f-45f7-b84a-62acdcdb205e.png)

**Comment by satva2** [comment]
when you say root of downloaded driver repository, i dont know exactly what you mean?

**Comment by ldrahnik** [comment]
As last time you did it fine. You do not have this driver repository. You have this one https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver. You are welcome.

**Comment by satva2** [comment]
are you sure? i did git clone https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver and still have issue. please bare with me tho man, i understand its frusterating working with someone who doesnt understand completely

**Comment by ldrahnik** [comment]
As is in the picture `git pull`, please run the same way `git remote show origin`.

**Comment by satva2** [comment]
ill figure it out.. thanks :)

**Comment by ldrahnik** [comment]
For getting this drive repository to your laptop please run `git clone git@github.com:asus-linux-drivers/asus-touchpad-numpad-driver.git`.

**Comment by ldrahnik** [comment]
@satva2 Confirmation for me that you had the wrong repository were sizes of files:

```
(base) ldrahnik@ZenbookUP5401EAUP5401EA5d04e179:~/projects/copy-driver$ git remote show origin
* remote origin
  Fetch URL: https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver
  Push  URL: https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver
  HEAD branch: main
  Remote branch:
    main tracked
  Local branch configured for 'git pull':
    main merges with remote main
  Local ref configured for 'git push':
    main pushes to main (up to date)
(base) ldrahnik@ZenbookUP5401EAUP5401EA5d04e179:~/projects/copy-driver$
(base) ldrahnik@ZenbookUP5401EAUP5401EA5d04e179:~/projects/copy-driver$ ls -la numpad_layouts
total 24
drwxrwxr-x 2 ldrahnik ldrahnik 4096 Sep 14 13:05 .
drwxrwxr-x 6 ldrahnik ldrahnik 4096 Sep 14 13:05 ..
-rw-rw-r-- 1 ldrahnik ldrahnik  619 Sep 14 13:05 gx701.py
-rw-rw-r-- 1 ldrahnik ldrahnik  539 Sep 14 13:05 m433ia.py
-rw-rw-r-- 1 ldrahnik ldrahnik  542 Sep 14 13:05 ux433fa.py
-rw-rw-r-- 1 ldrahnik ldrahnik  740 Sep 14 13:05 ux581l.py
```

**Comment by satva2** [comment]
i know... i see that. here is what happens now.
![Screenshot from 2022-09-14 07-07-00](https://user-images.githubusercontent.com/49539747/190138296-cefb44fc-dddd-4419-a071-1d1cc69d80a6.png)

**Comment by satva2** [comment]
ill try the command you gave me. as i downloaded it manually this last time. and tried. thanks.

**Comment by ldrahnik** [comment]
Np, using terminal is always win against clicking websites, a lot of mistakes happens to everyone because of that. One tab, another tab, the same driver name.. so driver is working fo you?

**Comment by satva2** [comment]
well.. im imagining it will. but.... now i have this problem
![Screenshot from 2022-09-14 07-10-54](https://user-images.githubusercontent.com/49539747/190138919-7c244b6a-df73-4e2a-a5fc-9ff400988123.png)

**Comment by satva2** [comment]
ugh im sorry. its early and im not focused.. as to what im doing

**Comment by satva2** [comment]
well this is why i switched to linux. there is a challenge. ill let you know when i get it and thanks for making it available,

**Comment by ldrahnik** [comment]
@sotva2 For using `git clone <ssh_url>` you need to have your public key uploaded to your github profile. Search google with something like `add public key to github profile`.

**Comment by satva2** [comment]
i got it. but this is what it says now... numpad isnt lighting up. 
![Screenshot from 2022-09-14 07-41-50](https://user-images.githubusercontent.com/49539747/190144699-adc386a8-8bb2-4997-b541-45cd9937d198.png)

**Comment by ldrahnik** [comment]
@satva2 Post result of command `sudo systemctl status asus_touchpad_numpad.service`.

**Comment by satva2** [comment]
![Screenshot from 2022-09-14 07-48-24](https://user-images.githubusercontent.com/49539747/190145699-5638ebd2-8c8b-4d93-9acc-37c7ce173426.png)

**Comment by ldrahnik** [comment]
@satva2 And result of status command after you run `sudo systemctl start asus_touchpad_numpad`?

**Comment by satva2** [comment]
is this what you meant? 

![Screenshot from 2022-09-14 07-52-19](https://user-images.githubusercontent.com/49539747/190146517-12df4e99-10b3-42ee-8539-26b481f9bd62.png)

**Comment by ldrahnik** [comment]
Ok, post here please entire content of this file (drivers log file): `/var/log/asus_touchpad_numpad-driver/error.log`

**Comment by satva2** [comment]
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by ldrahnik** [comment]
@satva2 Numpy python package is missing. What is output of `sudo dnf -y install python3-numpy`? Try run `sudo dnf -y install python3-numpy`.

**Comment by ldrahnik** [comment]
@satva2 Then try `sudo install.sh` again.

**Comment by satva2** [comment]
![Screenshot from 2022-09-14 08-09-36](https://user-images.githubusercontent.com/49539747/190149831-4e6962b6-0573-41e1-a90c-259ca381cf97.png)

**Comment by satva2** [comment]
really appreciate the time and effort man

**Comment by ldrahnik** [comment]
@satva2 Post log file again.

**Comment by ldrahnik** [comment]
@satva2 Feel free to put a star to this driver after it will be running.

**Comment by ldrahnik** [comment]
@satva2 Try run `pip3 install numpy` and then restart, then status, then watch log if does not running yet.

**Comment by satva2** [comment]
this is what it says... 
![Screenshot from 2022-09-14 08-19-28](https://user-images.githubusercontent.com/49539747/190151724-e6ac69ec-62ca-4830-9949-01325ba276b1.png)

**Comment by satva2** [comment]
should i jiust got ahead with the other stuff you said to do ? (restart driver...)

**Comment by ldrahnik** [comment]
No. Instead of `pip3` try `python3 -v` and post here your python3 version from which you can exit using writing `exit()` and then try `python3 -m pip install numpy`.

**Comment by satva2** [comment]
![Screenshot from 2022-09-14 08-25-35](https://user-images.githubusercontent.com/49539747/190152817-a73be6d7-0333-482d-ba1f-1d1e8c85ee47.png)

**Comment by ldrahnik** [comment]
Weird. Can you now try to run driver but via this: `LOG=DEBUG sudo -E ./asus_touchpad.py "up5401ea" ""` and post here result.

**Comment by satva2** [comment]
says command not found
 
![Screenshot from 2022-09-14 08-30-53](https://user-images.githubusercontent.com/49539747/190154005-cb914c4f-8643-43cc-b486-591f30cb9c0e.png)

**Comment by satva2** [comment]
oh oopos
whoa,. i apoligize

**Comment by satva2** [comment]
![Screenshot from 2022-09-14 08-32-21](https://user-images.githubusercontent.com/49539747/190154304-e9debfed-abc3-4a61-8c21-1ae0a78a6e69.png)

**Comment by ldrahnik** [comment]
@satva2 Do a `git pull` and then again run previous command for debugging driver but with your layout of course `LOG=DEBUG sudo -E ./asus_touchpad.py "g533" ""`

**Comment by satva2** [comment]
how do i find my exact layout?

**Comment by ldrahnik** [comment]
@satva2 `g533` should fit your laptop, during install.sh is detected automatically, during debugging you have to use name of file from folder `numpad_layouts`. So run `sudo -E ./asus_touchpad.py "g533" ""`.

**Comment by satva2** [comment]
it keeps doing this, after git pull

![Screenshot from 2022-09-14 08-52-39](https://user-images.githubusercontent.com/49539747/190158964-962f20b9-1326-4cb6-b1dd-2503f8aa5400.png)

**Comment by satva2** [comment]
installing but is not moving at all, so maybe problem between here and server or something

**Comment by satva2** [comment]
probably have to pick this up later im assuming..... it just says downloading packages,,, and remains on zero,

**Comment by satva2** [comment]
nevermind it completed,

**Comment by ldrahnik** [comment]
@satva2 When will be installed try to run again `sudo -E ./asus_touchpad.py "g533" ""`

**Comment by satva2** [comment]
![Screenshot from 2022-09-14 08-59-19](https://user-images.githubusercontent.com/49539747/190160548-2a414aed-67e9-4462-9aeb-e226b3bbafe8.png)

it just jeeos repeating saving config file

**Comment by ldrahnik** [comment]
@satva2 It's ok. Try open now NumberPad so hold top right icon for at least 1s, in this debugging mode.

**Comment by satva2** [comment]
its working

**Comment by ldrahnik** [comment]
@satva2 So exit this debugging driver and again `sudo systemctl start asus_touchpad_numpad` and then  `sudo systemctl status asus_touchpad_numpad` and it should be ok.

**Comment by satva2** [comment]
hey man youre a godsend. have a good day. :)

**Comment by ldrahnik** [comment]
@satva2 You can customize the driver via changes in file `numpad_layout/g533.py` (if is something missing or wrong, please make pull request or create issue here again, others use this layout also) in the repository and then remember to run `install.sh` again and other values not depending on your NumberPad model you can customize via config file `/usr/share/asus_touchpad_numpad-driver/asus_touchpad_numpad_dev`. Customization is described in the table in `Readme.MD` file.

**Comment by satva2** [comment]
ok. cool thanks. thumbs up
