### ISSUE TITLE
[Bug]: installation not persistant on reboot up5401ea

### ISSUE THREAD

**Issue by d4nkIot** [asus-linux-drivers/asus-touchpad-numpad-driver#78]
### Describe the bug

There are 2 scenarios where everything works perfectly on my Vivobook S 14 Flip (TP3402ZA)
1) during session after **sudo ./install.sh**
2) during troubleshoot via debug command in terminal

The issue is, if I restart the laptop, it stops working (nothing happens when touching the numpad numlock).
Then, when I either re-run installation or troubleshoot (start LOG=DEBUG), it starts working normally. 
However if I close the debug in terminal, then the numpad stops working again. 
Even more strange, if I stop debug while the backlight is lit up, actually it stays lit up permanently. The backlight will even be lit after a reboot, however nothing works (numbers, or numpad numlock).

Any idea what I am doing wrong?

### Expected behavior

After installation, stays persistent through reboot.

### Desktop

- Program version: Latest
- Distro: Arch Linux
- Kernel: 6.1.4-arch1-1

**Comment by ldrahnik** [comment]
Hello,
it looks like driver's service has not started after the laptop restart. Everything that you described supports this scenario. Restart and run `sudo systemctl status asus_touchpad_numpad` and please let me know the result.

**Comment by d4nkIot** [comment]
Thanks for getting back so fast!

![image](https://user-images.githubusercontent.com/122401482/211662826-9fdeba41-9666-4ef7-9e91-91157f7e91fb.png)

**Comment by d4nkIot** [comment]
and by the way..

Should the Main PID and Memory be changing this much after reinstalling with a reboot to get it to work?
Also the error about python-pip3, is this problematic?

![image](https://user-images.githubusercontent.com/122401482/211664851-af02d73c-e6fb-4bb2-8c0d-80b08e09983c.png)

**Comment by ldrahnik** [comment]
@d4nkIot 

> vendor preset: disabled

If you see a Vendor preset: Disabled, it means when the service first installs it will be disabled on start-up and will have to be manually started.

**Comment by ldrahnik** [comment]
@d4nkIot Arch pip3 package name should be fixed in master, thank you :)

**Comment by ldrahnik** [comment]
@d4nkIot What is your output for command `ls /etc/systemd/system/ -la | grep asus` ?

**Comment by d4nkIot** [comment]
Interesting... did not think that about preset: disabled.
Now indeed even restarting service will make everything work again after a reboot (non working state).

Here was the output you asked for:
![image](https://user-images.githubusercontent.com/122401482/211678805-4e4f819c-acaf-4f1f-8a25-b1f13983d0da.png)

Any idea why the systemd service would not be preset: enabled  after installation (or by manually enabling the service later)?
I am about to sleep, will check back tomorrow. Thanks again for the support!

**Comment by d4nkIot** [comment]
@ldrahnik good morning. regarding the **preset: disabled** on the service, I guess this should have no impact on this scenario. Is it not normal behavior for all services to default to this statue in Arch, due to the 99-default.preset file set to *disable ?
![image](https://user-images.githubusercontent.com/122401482/211735346-e74db973-fa9f-4650-9d07-1c1273cd2a1e.png)

e.g., the other asus drivers work fine on start with same preset (as well as all other services like NetworkManager, SDDM, etc):
![image](https://user-images.githubusercontent.com/122401482/211736158-491fa294-12a7-4caf-85c0-dabe2973b7f1.png)

**Comment by ldrahnik** [comment]
@d4nkIot You're right. Preset is not used in arch distro. Helped adding sleep to file `asus_touchpad.service`?

```
# For some operating systems with boot failure, adding this following property might resolve the issue  
#ExecStartPre=/bin/sleep 2
```

**Comment by ldrahnik** [comment]
@d4nkIot Look at systemd log file and attach result here please. Should be there all attempts of service start in case start failed.

**Comment by d4nkIot** [comment]
@ldrahnik adding sleep did not work unfortunately
![image](https://user-images.githubusercontent.com/122401482/211797108-b3ab4d85-0abf-4320-9212-0b3c23f57276.png)

**Comment by ldrahnik** [comment]
@d4nkIot For example like this `sudo journalctl --since today | grep asus`:

```
Jan 11 12:26:44 ZenbookUP5401EAUP5401EA5d04e179 systemd[1]: asus_touchpad_numpad_suspend.service: Succeeded.
Jan 11 12:26:44 ZenbookUP5401EAUP5401EA5d04e179 systemd[1]: asus_touchpad_numpad.service: Succeeded.
```

**Comment by d4nkIot** [comment]
last 7 reboots today (current session have not restarted service manually to get it to work)
previous session i manually restarted to get it to work before reboot
![image](https://user-images.githubusercontent.com/122401482/211799383-354b75a6-f36d-4aeb-9843-75e366ad8444.png)

**Comment by d4nkIot** [comment]
here with this **sudo journalctl --since today | grep asus**:

![image](https://user-images.githubusercontent.com/122401482/211799892-98118c22-f69d-4588-a266-83ae61465f0b.png)

**Comment by ldrahnik** [comment]
@d4nkIot Could you please try an attempt with reinstalled the driver with non-xorg-11 service. Do a change in `install.sh` like this: [line 13] wayland_or_x11="foobar"

**Comment by d4nkIot** [comment]
and 1 more screenshot from  log, showing the process start normally after force restart in session
![image](https://user-images.githubusercontent.com/122401482/211802531-a191a1b1-ede8-4a37-9525-d15e0a72186e.png)

**Comment by d4nkIot** [comment]
> @d4nkIot Could you please try an attempt with reinstalled the driver with non-xorg-11 service. Do a change in `install.sh` like this: [line 13] wayland_or_x11="foobar"
> 
> Co we could exclude a problem with different type `simple`, `idle`, Environment rows.. and because of that variables another target `graphical.target`.

okay, let me check it in a moment

**Comment by ldrahnik** [comment]
@d4nkIot Why is on the last screenshot in the last non-yellow row written `"...servic"` and not `"...service"`?

**Comment by d4nkIot** [comment]
@ldrahnik both yellows are systemctl restart... not sure why the previous one at 13:59 is missing an e..... now it has it though, same behavior.
![image](https://user-images.githubusercontent.com/122401482/211805447-a795870d-adf3-4794-ac3f-3064ccdc0334.png)

**Comment by ldrahnik** [comment]
@d4nkIot No problem, unfortunately, I have no more ideas atm. Is weird that other services have no problem with starting after boot.

**Comment by ldrahnik** [comment]
@d4nkIot Please attach log file `cat /var/log/asus_touchpad_numpad-driver/error.log`, best with clear installed (reinstalled) driver and after reboot.

**Comment by d4nkIot** [comment]
yes very strange indeed. 
here is 1 more screenshot of all 3 drivers after reboot (sorry for so many :D)
![image](https://user-images.githubusercontent.com/122401482/211810008-d85b6880-6e91-4313-9102-95688900abaa.png)

-yellow box is again where prior numpad driver is not working, but works after
-green box is the last mention of touchpad_numpad , whereas the other 2 (fliplock, wmi_hotkeys) cycle through start/stop few more times and successfully start and function in session
.. so my question is, what causes the fliplock and wmi_hotkeys to have **status=1/failure**, thus causing a restart job to successfully get them working

**Comment by d4nkIot** [comment]
> @d4nkIot Please attach log file `cat /var/log/asus_touchpad_numpad-driver/error.log`, best with clear installed (reinstalled) driver and after reboot.
[asus-touchpad_numpad-driver-error.log](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/files/10392545/asus-touchpad_numpad-driver-error.log)
here you go

**Comment by d4nkIot** [comment]
here from logfile is result from restarting service to get it to work

```
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
INFO:Pad:Detecting keyboard from string: "N: Name="AT Translated Set 2 keyboard""
INFO:Pad:Set keyboard 4 from H: Handlers=sysrq kbd leds event4
INFO:Pad:Detecting touchpad from string: "N: Name="ASUE140D:00 04F3:31BC Touchpad""
INFO:Pad:Set touchpad device id 14 from S: Sysfs=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-14/i2c-ASUE140D:00/0018:04F3:31BC.0001/input/input18
INFO:Pad:Set touchpad id 8 from H: Handlers=event8 mouse1
INFO:Pad:Touchpad min-max: x 0-3880, y 0-2299
INFO:Pad:Numpad min-max: x 200-3680, y 200-2219
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
```

**Comment by ldrahnik** [comment]
@d4nkIot Please try add more seconds, so add line `ExecStartPre=/bin/sleep 60 # 60 seconds` and reinstall, restart so we can figure out its not just problem with timing

**Comment by d4nkIot** [comment]
now it actually just stuck in activating state, and keeps bouncing from 0 to 60 seconds, and repeating.
never becomes **active **(running)** status**
![image](https://user-images.githubusercontent.com/122401482/211818089-8910cceb-d177-4006-94f0-7919ccf00a16.png)

**Comment by d4nkIot** [comment]
with 4 seconds service can be active (run), however in the log:

`INFO:Pad:Detecting keyboard from string: "N: Name="AT Translated Set 2 keyboard""
INFO:Pad:Set keyboard 4 from H: Handlers=sysrq kbd leds event4
INFO:Pad:Detecting touchpad from string: "N: Name="ASUE140D:00 04F3:31BC Touchpad""
INFO:Pad:Set touchpad device id 14 from S: Sysfs=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-14/i2c-ASUE140D:00/0018:04F3:31BC.0004/input/input10
INFO:Pad:Set touchpad id 10 from H: Handlers=event10 mouse2
INFO:Pad:Touchpad min-max: x 0-3880, y 0-2299
INFO:Pad:Numpad min-max: x 200-3680, y 200-2219
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed
ERROR:Pad:Listening touchpad events unexpectedly failed
Unable to connect to X server
INFO:Pad:Getting Device Enabled via xinput failed`

doesn't give 'can't find touchpad' error, however still gives 'listening touchpad events unexpectedly failed' error == not working :(((

**Comment by ldrahnik** [comment]
@d4nkIot Please try in file `asus_touchpad.py` [1299:1303] remove `try` and `except` blocks so the origin exception will not be consumed and not transformed to this error.

**Comment by d4nkIot** [comment]
@ldrahnik you mean remove lines 1299:1303 completely? or only try and except?
![image](https://user-images.githubusercontent.com/122401482/211834995-569d40a7-2cc3-4353-9a9a-aa62a637f4bd.png)

**Comment by d4nkIot** [comment]
I am guessing this is what it means (that language going beyond my scope of understanding :) )..
![image](https://user-images.githubusercontent.com/122401482/211837545-3b5e0633-6756-4a24-b0c1-3e4aa9908de4.png)
now does not work at all
![image](https://user-images.githubusercontent.com/122401482/211837696-415f6284-b1dc-48e4-a617-b7c403a8efa1.png)

**Comment by ldrahnik** [comment]
@d4nkIot Np, instead of this:

```
try:
    listen_touchpad_events()
except:
    log.error("Listening touchpad events unexpectedly failed")
    sys.exit(1)
```

this (without spaces/tab before because on indent in python lang does matter)

```
listen_touchpad_events()
```

**Comment by d4nkIot** [comment]
@ldrahnik hello. find 4 log cases here:
[compiled error log.log](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/files/10401260/compiled.error.log.log)

1) pulled latest master, reinstalled, cleared log, reboot = not working
2) restart service in same session = working
3) changed bin/sleep timer 2, reboot = not working
4) restart service in same session = working

**Comment by ldrahnik** [comment]
@d4nkIot Nice clear report, thank you. Attempts have been done using `asus_touchpad.X11.service`?

**Comment by ldrahnik** [comment]
@d4nkIot About input id's do not worry, when is driver started every time is created new new input device for sending characters/numbers. Its done asynchronously, so sometimes is input<xyz> higher, sometimes lower. Who comes first have better place..

**Comment by d4nkIot** [comment]
@ldrahnik correct, X11 on KDE with SDDM.
++ gotcha on the touchpad device numbering.

**Comment by ldrahnik** [comment]
@d4nkIot **Summary:** It still looks like the driver is just starting too early, nothing else. 2 reasons, the first is `x11` because is a problem with connecting to the main display, does not exist yet, `x11` init is not finished and then we are not able to check the status of the touchpad device because for checking is used `xinput`, the tool which is under `x11` and `x11` is not started yet. Not started `x11` yet describe these rows in the error log:

```
Invalid MIT-MAGIC-COOKIE-1 key
Unable to connect to X server
INFO:asus-touchpad-numpad-driver:Getting Device Enabled via xinput failed
```

> Some people may suggest graphical.target on the system bus, but the problem with this is you need to manually set the > $DISPLAY and $XAUTHORITY environment variables in your service, you need to set User= and it will try to start when 
> reaching the display manager login screen instead of when the desktop environment is started.
(https://unix.stackexchange.com/questions/666509/systemd-service-does-not-start-wantedby-multi-user-target)

I have no exp it could be a problem, I use `x11` and `graphical.target` does not do the problem for me (`Ubuntu20.04`), `x11` is initialized already but it might do a problem as is described in this comment in stackowerflow especially when you, for example, use more monitors and any tool/configurator package for them.


The second problem is when we try not to check the status! but when we are trying listening touchpad device it says does not exist:

```
unable to find device ASUE140D:00 04F3:31BC Touchpad

Traceback (most recent call last):
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 1300, in <module>
    listen_touchpad_events()
  File "/usr/share/asus_touchpad_numpad-driver/asus_touchpad.py", line 1055, in listen_touchpad_events
    for e in d_t.events():
  File "/usr/lib/python3.10/site-packages/libevdev/device.py", line 536, in events
    ev = self._libevdev.next_event(flags)
  File "/usr/lib/python3.10/site-packages/libevdev/_clib.py", line 893, in next_event
    raise OSError(-rc, os.strerror(-rc))
OSError: [Errno 19] No such device
unable to find device ASUE140D:00 04F3:31BC Touchpad
```

**What we could test more?** I would like to confirm or refute that the second problem is connected to `X11`. Could you again please change the row in `install.sh[13]: wayland_or_x11="foobar"` and do the same report as you did without postponing driver start?

**Comment by ldrahnik** [comment]
@d4nkIot Please, could you try again? Please pull master. What's bothering me is keyboard device is loaded, every time, and touchpad device is at the same moment not found, it can be because adding input device consumes more time, for example, I do not know. So I added printing entire list of devices at that moment `/proc/bus/input/devices`. I already have there a touchpad device added, it is weird: `ERROR:asus-touchpad-numpad-driver:N: Name="ASUE140D:00 04F3:31B9 Touchpad"`. I would compare that list with list of all devices when is laptop started. Could you do that? What I am interested in is Q: Is touchpad only device what is all time missing? Or are missing more devices? Missing more devices could confirm driver is loading too early.

**Comment by d4nkIot** [comment]
@ldrahnik sure, here is after pulling master and reinstalling: [error.log](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/files/10402379/error.log)

**Comment by ldrahnik** [comment]
@d4nkIot Could you please try it now? I pushed to master change - I added a line to the service unit `BindsTo=graphical.target`. Git pull, reinstall, restart laptop, `sudo systemctl status asus_touchpad_numpad.service`, post driver log here `/var/log/asus_touchpad_numpad-driver/error.log`. Thank you for testing, I would like to solve this if possible.

**Comment by d4nkIot** [comment]
@ldrahnik sure thing! 
[restart-after-line-106.log](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/files/10419780/restart-after-line-106.log)

**Comment by ldrahnik** [comment]
@d4nkIot Could you please try branch `78-not-started-driver`, reinstall, restart and attach the entire log again.

**Comment by d4nkIot** [comment]
@ldrahnik here it is
[78-not-started-driver-branch.log](https://github.com/asus-linux-drivers/asus-touchpad-numpad-driver/files/10479081/78-not-started-driver-branch.log)

**Comment by ldrahnik** [comment]
@d4nkIot And this version of `is_x11_started.sh`:

```
#!/bin/bash

if ! xset q &>/dev/null; then
    echo "No X server at \$DISPLAY [$DISPLAY]" >&2
    exit 1
fi
```

I am only interested if is printed `echo "No X server at \$DISPLAY [$DISPLAY]" >&2` or not. Thank you a lot.

**Comment by d4nkIot** [comment]
@ldrahnik ![x-is-up](https://user-images.githubusercontent.com/122401482/214049302-56bf9cdc-1b88-424e-a938-14548e9445d3.png)

**Comment by ldrahnik** [comment]
@d4nkIot Badly described, of course, is necessary to edit file `is_x11_started.sh` and install it again when is NumberPad driver starting but I do not need to attach the entire log, that was what I tried to say.

**Comment by d4nkIot** [comment]
ah gotcha..
give me a moment

**Comment by d4nkIot** [comment]
@ldrahnik
```
No X server at $DISPLAY [:0]
```
![x-no-display](https://user-images.githubusercontent.com/122401482/214051462-86044d91-efe9-4b2f-a3ca-c3818723679b.png)

**Comment by ldrahnik** [comment]
@d4nkIot Please again reinstall, restart and this time again attach entire log, I added to service line: `After=graphical.target systemd-user-sessions.service`, might be helpful

**Comment by d4nkIot** [comment]
@ldrahnik I will try again.
I was searching few things, and came across this: 
https://wiki.archlinux.org/title/SDDM#X_authority_(aka_MIT-MAGIC-COOKIE)_file
--> https://github.com/sddm/sddm/issues/622#issuecomment-451777466

Do you think this is related (I use KDE - SDDM) since the previous logs were also throwing the similar errors mentioned? 
```
Invalid MIT-MAGIC-COOKIE-1 key
Unable to connect to X server
ERROR:asus-touchpad-numpad-driver:Getting Device Enabled via xinput failed
```

**Comment by ldrahnik** [comment]
@d4nkIot Did you test that service proposal from mentioned git issue? Important what i think is test:

```
Requires=display-manager.service
After=display-manager.service
```

**Comment by d4nkIot** [comment]
@ldrahnik Here are the only 5 lines in log, from the updated branch. Same failed status as above as well.
```
No X server at $DISPLAY [:0]
No X server at $DISPLAY [:0]
No X server at $DISPLAY [:0]
No X server at $DISPLAY [:0]
No X server at $DISPLAY [:0]
```
I have not tested out what was suggested on the git issue, I will have more time later tonight to try.

**Comment by ldrahnik** [comment]
@d4nkIot Please let me know about any progress.

**Comment by d4nkIot** [comment]
@ldrahnik Hi, sorry been quite busy last few days.
As mentioned above, the error message shows no X server with the previous pull from git branch you updated.
I tried a 2 different edited variations on the service suggested from that SDDM git issue, without success. I need to look in more detail, and try some other ones later today or tomorrow when I have time.

**Comment by d4nkIot** [comment]
@ldrahnik Hi. FYI, I just had some time to test things out today... actually I got the updated master, reinstalled, and now it works as intended! Issues are gone :)
